version: '3'
services:
  app:
    build: .
    ports:
      - '3030:3000'
    volumes:
      - .:/app
    depends_on:
      - db
    command: ["./start.sh"]
  db:
    container_name: gorm-test
    platform: linux/x86_64
    image: mysql:8.0.21
    ports:
      - '3306:3306'
    volumes:
      - go_mysql_data:/var/lib/mysql
    environment:
      MYSQL_USER: 'webuser'
      MYSQL_PASSWORD: 'webpass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'go_mysql8_development'
volumes:
  go_mysql_data:
